name: gcp_dbt_project
version: '1.0'
config-version: 2

# MUST match the profile name in ~/.dbt/profiles.yml
profile: 'gcp_dbt_project'

# Project paths
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Variables used in your SQL (we referenced this in staging models)
vars:
  project_id: "sinuous-network-468812-j8"

# Model configs
models:
  gcp_dbt_project:
    +materialized: table
    staging:
      +schema: transformed_dbt_dataset
    marts:
      +schema: transformed_dbt_dataset



