version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_unique_id
        tests: [not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_purchase_timestamp
        tests: [not_null]

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: order_item_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: price
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_sellers
    columns:
      - name: seller_id
        tests: [not_null, unique]

  - name: stg_geolocation
    columns:
      - name: geolocation_zip_code_prefix
        tests: [not_null]

